# Site settings
title: Office of the Federal Chief Information Officer
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
#
baseurl: "/policy-v2" # the subpath of your site, e.g. /blog
url: "https://policy.cio.gov" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

# Put the information about your site's GitHub repository if it is public
repo_url: https://github.com/ombegov/policy-v2

collections: 
  overview:
    output: true
    permalink: /:path/
    url: /
    status: home 
    title: Welcome
    githublabel: Home
  drafts_overview:
    output: true
    permalink: /drafts/:path/
    url: /drafts/
    status: draft
    title: Draft Policies
    githublabel: Draft Policies
  finalized_overview:
    output: true
    permalink: /finalized/:path
    url: /finalized/
    status: finalized
    title: Finalized Policies
    githublabel: Finalized Policies
  resources_overview:
    output: true
    permalink: /resources/:path/
    url: /resources/
    status: resource
    title: Agency Resources
    githublabel: Agency Resources
  fitara:
    output: true
    permalink: /fitara/:path/
    url: /fitara/
    status: finalized
    title: "M-15-14: Management and Oversight of Federal Information Technology"
    githublabel: fitara
  fitara-resources:
    output: true
    permalink: /fitara-resources/:path/
    url: /fitara-resources/
    status: resource
    title: FITARA resources
    githublabel: fitara
  cyber-acquisitions:
    output: true
    permalink: /cybersecurity-protections-in-federal-acquisitions/:path/
    url: /cybersecurity-protections-in-federal-acquisitions/
    status: draft
    title: Improving Cybersecurity Protections in Federal Acquisitions
    githublabel: Cybersecurity